apiVersion: provider.upcloud.com/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: upcloud-crossplane-example-credentials
      namespace: upcloud-crossplane-example
      key: credentials
---
apiVersion: provider.m.upcloud.com/v1beta1
kind: ProviderConfig
metadata:
  name: upcloud-crossplane-example-providerconfig
  namespace: upcloud-crossplane-example
spec:
  credentials:
    source: Secret
    secretRef:
      name: upcloud-crossplane-example-credentials
      namespace: upcloud-crossplane-example
      key: credentials
